# Production deployment configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

version: '3.8'

services:
  noisefs-daemon:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    environment:
      - NOISEFS_LOG_LEVEL=warn
      - NOISEFS_CACHE_SIZE=1000000
      - NOISEFS_MAX_CONNECTIONS=100
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  noisefs-webui:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - NOISEFS_LOG_LEVEL=warn
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Load balancer for production
  nginx:
    image: nginx:alpine
    container_name: noisefs-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    networks:
      - noisefs-network
    depends_on:
      - noisefs-webui
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"