apiVersion: v1
kind: PersistentVolume
metadata:
  name: noisefs-data-pv
  labels:
    app: noisefs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: noisefs-storage
  nfs:
    server: nfs-server.example.com  # Replace with your NFS server
    path: /path/to/noisefs/data     # Replace with your NFS path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: noisefs-data
  namespace: noisefs
  labels:
    app: noisefs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: noisefs-storage

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: noisefs-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true